Update database
CodeYourFuture/scot-volunteer-ad pull request #27
Opened 2020-11-22 22:02 UTC by roza8765

2020-11-23 13:55 UTC, aaitken80 submitted a review, later dismissed
Schema definition matches what was discussed.

2020-11-23 14:10 UTC, aaitken80 requested changes
in the TOPIC table document_name and document_link are set to NOT NULL when they are optional fields. I don't know the requirement's here but might need to know the volunteer's name as well as their email address? That was in the previous model.

2020-11-23 15:00 UTC, roza8765 commented
yes but I think we don't need the volunteer name as we just sent the block to their email

2020-11-23 15:02 UTC, roza8765 commented
and for the topic part, I think it is required to have  document_name and document_link  as not null

2020-11-23 22:03 UTC, aaitken80 requested changes

2020-11-23 22:03 UTC, aaitken80 commented on server/db/populate-db.sql
> +INSERT INTO blocks (block_id, block_name) VALUES(1, 'Block 1');
block_id is set to GENERATED so you cannot insert a value into it here

2020-11-23 22:03 UTC, aaitken80 commented on server/db/populate-db.sql
> +INSERT INTO topics (topic_id, topic_name, document_name, document_link) VALUES(1, 'Beginners English', 'Beginners English', 'www.google.com');
topic_id is set to GENERATED so you cannot insert a value into it here

2020-11-23 22:03 UTC, aaitken80 commented on server/db/populate-db.sql
> +INSERT INTO volunteer_topic (volunteer_topic_id, topic_id, volunteer_id) VALUES(1, 1, 1);
volunteer_topic_id is set to GENERATED so you cannot insert a value into it here.

You are trying to insert a volunteer_id before the volunteer table is populated, you need to move the section 33-34 to above this section.

2020-11-23 22:03 UTC, aaitken80 commented on server/db/populate-db.sql
> +INSERT INTO volunteer_answers (volunteer_topic_id, question_id, answers) VALUES(1, 1, 'Past simple, past continus');
The column name is answer, not answers here.

2020-11-24 09:04 UTC, aaitken80 approved these changes

2020-11-24 09:05 UTC, merged